:pidfile: ./sidekiq.pid
:daemon: true

development:
  :verbose: true
  :logfile: ./log/sidekiq-development.log
  :concurrency: 5
  :timeout: 30
  :queues:
    - mailers

production:
  :verbose: false
  :logfile: ./log/sidekiq-production.log
  :concurrency: 10
  :timeout: 5
  :queues:
    - mailers